version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: microRabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
  redis:
    image: redis
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      # - ./redis/data:/data
      - cache:/data
volumes:
  cache:
    driver: local